MyWebsite/Controllers/BlogController.cs
using Microsoft.AspNet.Identity;
using MyWebsite.Models;
using MyWebsite.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MyWebsite.Controllers
{
    public class BlogController : Controller
    {
        //TODO: update createdAt properties

        public readonly IBlogPostService _postService;

        //public BlogController():this(new DefaultBlogPostService(new ApplicationDbContext())) { }
        
        public BlogController(IBlogPostService postService) {
            _postService = postService;
        }

        // GET: Blog
        public async Task<ActionResult> Index(CancellationToken ct)
        {
            var posts = await _postService.GetPostsAsync(ct);
            return View(posts);
        }
        
        // GET: Blog/Details/5
        public async Task<ActionResult> Details(Guid id,CancellationToken ct)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            
            ViewBag.blogPostId = id;
            TempData["UserId"] = User.Identity.GetUserId();
            //TODO: create helper method to display Image inside the Model
            var post = await _postService.GetPostByIdAsync(id, ct);

            if (post == null) return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            
            return View(post);
        }

        /*[Authorize]
        [HttpPost]
        [ActionName("Details")]
        public async Task<ActionResult> Details(Comment comment, CancellationToken ct) {
            await _commentService.CreateCommentAsync(comment, ct);
            return Redirect(Request.UrlReferrer.ToString());
        }*/

        // GET: Blog/Create
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Blog/Create
        [HttpPost]
        [Authorize(Roles ="Admin")]
        public async Task<ActionResult> Create(BlogPost post,CancellationToken ct)
        {
            try
            {
                //if (ModelState.IsValid)
                {
                    var userId = User.Identity.GetUserId();
                     var createdPost = await _postService.CreatePostAsync(post,userId, ct);

                     return RedirectToAction("Details", new { id = createdPost.Id });
                }
                //return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Blog/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(Guid id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            //TODO: use Automapper to clean up the code
            var post = _postService.GetPostById(id);

            if (post == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            return View(post);
        }

        // POST: Blog/Edit/5
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(Guid id, BlogPost post, CancellationToken ct)
        {
            try
            {
                await _postService.UpdatePostAsync(id,post, ct);

                return RedirectToAction("Details", new { id = id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Blog/Delete/5
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(Guid id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var post = _postService.GetPostById(id);
            if (post == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            return View(post);
        }

        // POST: Blog/Delete/5
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(Guid id, CancellationToken ct)
        {
            try
            {
                if (id == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                await _postService.RemovePostAsync(id,ct);
                
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MyWebsite/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyWebsite.Models;
using Microsoft.AspNet.Identity;

namespace MyWebsite.Controllers
{
    public class MoviesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Movies
        public ActionResult Index(string searchString, string MovieGenre)
        {
            var movieQuery = from m in db.Movies select m;

            var movieGenre = from m in db.Movies orderby m.Genre select m.Genre;

            ViewBag.MovieGenre = new SelectList(movieGenre.Distinct());

            if (!String.IsNullOrEmpty(searchString))
            {
                movieQuery = movieQuery.Where(m => m.Title.Contains(searchString));
            }

            if (!String.IsNullOrEmpty(MovieGenre)) {
                movieQuery = movieQuery.Where(m => m.Genre.Equals(MovieGenre));
            }
            
            return View(movieQuery);
        }

        // GET: Movies/Details/5
        public ActionResult Details(Guid? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MovieEntity movieEntity = db.Movies.Find(id);
            if (movieEntity == null)
            {
                return HttpNotFound();
            }
            return View(movieEntity);
        }

        // GET: Movies/Create
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "Id,Title,Genre,Image,ReleasedDate,Plot,Price")] MovieEntity movieEntity)
        {
            if (ModelState.IsValid)
            {
                movieEntity.Id = Guid.NewGuid();
                db.Movies.Add(movieEntity);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(movieEntity);
        }

        // GET: Movies/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MovieEntity movieEntity = db.Movies.Find(id);
            if (movieEntity == null)
            {
                return HttpNotFound();
            }
            return View(movieEntity);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Id,Title,Genre,Image,ReleasedDate,Plot,Price")] MovieEntity movieEntity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(movieEntity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(movieEntity);
        }

        // GET: Movies/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MovieEntity movieEntity = db.Movies.Find(id);
            if (movieEntity == null)
            {
                return HttpNotFound();
            }
            return View(movieEntity);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(Guid id)
        {
            MovieEntity movieEntity = db.Movies.Find(id);
            db.Movies.Remove(movieEntity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admin")]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyWebsite/Views/Shared/_LandingLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/landingcss")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Forum","Index","Blog")</li>
                    <li>@Html.ActionLink("Movie Store","Index","Movies")</li>
                    <li><a href="~/API/Root.html">IceCream Api</a></li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MyWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>